### ISSUE TITLE
ErrorException on dependencies

### ISSUE THREAD

**Issue by elypsia-allopneus** [franzholz/tt_board#2]
Hi,

I'm trying to use your extention on my Typo3 v8.7.8 because it's flagged as compatible with Typo3 v8
I download all dependencies and trying to install with composer.
* jambagecom/tt-board (1.9.3)
* jambagecom/div2007 (1.7.18)
* jambagecom/tslib_fetce (0.3.1)

I get warning messages and ErrorException when the autoload file try to be generated. This issue break my site because autoload is not generated.

Seems there is issue with dependancies:
```
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing jambagecom/tslib_fetce (0.3.1): Downloading (100%)
  - Installing jambagecom/div2007 (1.7.18): Loading from cache
  - Installing jambagecom/tt-board (1.9.3): Downloading (100%)
Writing lock file
Generating autoload files
Warning: Ambiguous class resolution, "t3lib_extMgm" was found in both "/mnt/sources/web/typo3conf/ext/div2007/class.tx_div2007_compatibility6.php" and "/mnt/sources/web/typo3conf/ext/div2007/Migrations/Code/LegacyClassesForIde.php", the first will be used.
Warning: Ambiguous class resolution, "t3lib_parsehtml" was found in both "/mnt/sources/web/typo3conf/ext/div2007/class.tx_div2007_compatibility6.php" and "/mnt/sources/web/typo3conf/ext/div2007/Migrations/Code/LegacyClassesForIde.php", the first will be used.
Warning: Ambiguous class resolution, "t3lib_div" was found in both "/mnt/sources/web/typo3conf/ext/div2007/class.tx_div2007_compatibility6.php" and "/mnt/sources/web/typo3conf/ext/div2007/Migrations/Code/LegacyClassesForIde.php", the first will be used.
Warning: Ambiguous class resolution, "tslib_cObj" was found in both "/mnt/sources/web/typo3conf/ext/div2007/class.tx_div2007_compatibility6.php" and "/mnt/sources/web/typo3conf/ext/div2007/Migrations/Code/LegacyClassesForIde.php", the first will be used.
Warning: Ambiguous class resolution, "tslib_fe" was found in both "/mnt/sources/web/typo3conf/ext/div2007/class.tx_div2007_compatibility6.php" and "/mnt/sources/web/typo3conf/ext/div2007/Migrations/Code/LegacyClassesForIde.php", the first will be used.

Installation failed, reverting ./composer.json to its original content.

  [ErrorException]
  Use of undefined constant TYPO3_version - assumed 'TYPO3_version'
```

Could you please tell me if you have a workaround or how to fix maybe use the code of the master ? i see some new commits but no new release.

Many thanks.

**Comment by franzholz** [comment]
What happens if you remove this file?

"/mnt/sources/web/typo3conf/ext/div2007/class.tx_div2007_compatibility6.php"

**Comment by elypsia-allopneus** [comment]
if i remove this file and warnings disappear but ErrorException is still there
```
Installation failed, reverting ./composer.json to its original content.

  [ErrorException]
  Use of undefined constant TYPO3_version - assumed 'TYPO3_version'
```

**Comment by franzholz** [comment]
I have search tt_board 1.9.3 and div2007 1.7.8. There is not constant TYPO3_version used. div2007 only uses it as a key value of an associative array.
Maybe you use an older version.

  [franz@localhost div2007]$ find  . -name '*.*'  -exec  grep   "'TYPO3_version'"  {}  \;  -ls  
  grep: .: Ist ein Verzeichnis
			  $eInfo['TYPO3_version'] = $extConf['constraints']['depends']['typo3'];
			  $eInfo['TYPO3_version'] = $extConf['TYPO3_version'];
  317193    8 -rw-rw-r--   1 franz    franz        5389 Jan 31 10:17 ./Classes/Utility/ExtensionUtility.php
					  $eInfo['TYPO3_version'] = $EM_CONF[$extKey]['constraints']['depends']['typo3'];
					  $eInfo['TYPO3_version'] = $EM_CONF[$extKey]['TYPO3_version'];
						  $eInfo['TYPO3_version'] = $extConf['constraints']['depends']['typo3'];
						  $eInfo['TYPO3_version'] = $extConf['TYPO3_version'];
  317148   64 -rw-rw-r--   1 franz    franz       63504 Jan 31 10:17 ./class.tx_div2007_alpha.php
						  $eInfo['TYPO3_version'] = $extConf['constraints']['depends']['typo3'];
						  $eInfo['TYPO3_version'] = $extConf['TYPO3_version'];
  317149  112 -rw-rw-r--   1 franz    franz      114433 Jan 31 10:17 ./class.tx_div2007_alpha5.php

**Comment by elypsia-allopneus** [comment]
I found this 
```
class.tx_div2007_alpha.php:1496:                if (version_compare(TYPO3_version, '6.2.0', '>=')) {
class.tx_div2007_core.php:81:                   $result = call_user_func($callingClassName . '::convertVersionNumberToInteger', TYPO3_version);
class.tx_div2007_core.php:86:                   $result = t3lib_utility_VersionNumber::convertVersionNumberToInteger(TYPO3_version);
class.tx_div2007_core.php:91:                   $result = t3lib_div::int_from_ver(TYPO3_version);
class.tx_div2007_core.php:471:                  version_compare(TYPO3_version, '6.2.0', '<') ||
class.tx_div2007_core.php:505:            version_compare(TYPO3_version, '7.0.0', '>=') &&
class.tx_div2007_core.php:559:                  version_compare(TYPO3_version, '7.0.0', '>=') &&
class.tx_div2007_core.php:592:            version_compare(TYPO3_version, '8.0.0', '>=') &&
class.tx_div2007_core.php:631:            version_compare(TYPO3_version, '8.0.0', '>=')
class.tx_div2007_email.php:168:                 version_compare(TYPO3_version, '4.7.0', '>=') ||
class.tx_div2007_email.php:181:                         version_compare(TYPO3_version, '6.0.0', '<') &&
Classes/Base/LocalisationBase.php:85:        $this->typoVersion = \TYPO3\CMS\Core\Utility\VersionNumberUtility::convertVersionNumberToInteger(TYPO3_version);
Classes/Base/LocalisationBase.php:271:        if (version_compare(TYPO3_version, '7.4.0', '>')) {
Classes/Utility/MailUtility.php:84:             if (version_compare(TYPO3_version, '6.2.0', '<')) {
Classes/Utility/TableUtility.php:82:            $typoVersion = \TYPO3\CMS\Core\Utility\VersionNumberUtility::convertVersionNumberToInteger(TYPO3_version);
ext_localconf.php:40:if (version_compare(TYPO3_version, '8.0.0', '>=')) {
lib/class.tx_div2007_staticinfotables.php:640:                  version_compare(TYPO3_version, '6.2.0', '<')
Migrations/Code/ClassAliasMapResult.php:940:if (version_compare(TYPO3_version, '8.0.0', '>=')) {
```

**Comment by franzholz** [comment]
Sorry, I made a wrong search using single quotes.

Wrong order.
It seems that the extension div2007 is called after TYPO3. This is the only explanation I can think of.
The composer.json already has this requirement:

  "require": {
    "typo3/cms-core": ">=7.6.0,<8.99.99",

There seems to be a failure somewhere. You should ask someone else, e.g. at Stackoverflow.lcom . I have no more ideas.

**Comment by franzholz** [comment]
I have created a new version 1.7.19 of extension div2007.

https://github.com/franzholz/div2007/commit/7daf9131245e47d4a8d44be8a35f9b5ea5177444
