### ISSUE TITLE
Postform not showing

### ISSUE THREAD

**Issue by Asfga** [franzholz/tt_board#3]
Hi,

I just installed your extension because I want to have some type of forum on my page but I can't see the postform to create new threads or posts. I followed the official typo3 documentation but there is no word on how to add a postform or even to handle it. Added a content element with the Code:Postform but nothing to see.
Lots of old threads (almost every thread is 10 years old) I found on google had the same problem, but solutions from there weren't working.

Does anyone have an idea why the postform is hidden?

**Comment by franzholz** [comment]
Then you did not read the manual which says that the postform is by default only visible to registered front end users. This is for security reasons. You cannot install the forum without making any thougths about spammers. Spammers will use the forum to send emails to any persons. You can use the spam filter in the extension.

set memberOfGroups = 0 to allow any user.

**Comment by Asfga** [comment]
Have this line of code in my constant section like the documentation says it. Also logged in and out to see if there is a difference but still no visible postform. :/

**Comment by franzholz** [comment]
you must have one of these in the constants:

with front end users:

    plugin.tt_board {
      memberOfGroups = 4,5,7
    }

without front end users:

    plugin.tt_board {
       memberOfGroups = 0
    }

Can you see something in the front end HTML source code?
Or is anything written into the PHP error_log file?

recheck it in the TypoScript object browser if this constant is really there.

**Comment by Asfga** [comment]
Okay I found my mistake...I put the code snippet in an extern file and added it in the constant with typoscript include file. When I directly add the code in the constant field it works.

**Comment by Asfga** [comment]
Now that I can work with the form there is another small question...can I change the html of the form for example add classes to labels + inputs? Just found a way for the notify and submit label but for others don't work that

**Comment by franzholz** [comment]
Use the constant "file.templateFile" of "plugin.tt_board_tree" or "plugin.tt_board_list" to use your own HTML template. Copy the template file from tt_board to a subfolder of fileadmin. There you can adapt the HTML to any HTML valid format you want.

**Comment by Asfga** [comment]
Yeah I'm using a custom template by changing the original a little here and there but I found no markers for the postform to customize it. I could copy the form from html when loaded my site but then I couldn't use e.g. the automatic input filling feature when an user is logged it. Sorry for bothering you with my questions..

**Comment by franzholz** [comment]
The form uses still an outdated code.
However it is possible to postform.dataArray in Typoscript. 

Have a look into the setup.txt:

plugin.tt_board_list < temp.tt_board.shared
plugin.tt_board_tree < temp.tt_board.shared

Both have a part postform.dataArray. You can make your own additions there or change the default setup.
