### ISSUE TITLE
check of MX record for email fails

### ISSUE THREAD

**Issue by typo3max** [franzholz/tt_board#38]
Wann kommt die neue Version für TYPO3 12. Liebe deine Board Extension. vielleicht könntest du irgendwann die funktion einbauen das man Bilder integrieren kann.

Danke und Gruß Holzinger

**Comment by franzholz** [comment]
Only in English here!

**Comment by typo3max** [comment]
THe latest version from the board extension has some issues!
Sry, we need a new version of TYPO3 12 board extension. i love your board extension, maybe you can expand the extension with image function. 
Thank you Holzinger

**Comment by typo3max** [comment]
Boar Holzinger, there are issues in forum list.php

**Comment by typo3max** [comment]
Holzinger, der PHP vesions chaos... es klatscht bald aber keinen Applaus! ^^

**Comment by franzholz** [comment]
Only English.
Send me a private E-Mail with access to a test site where an error happens.

**Comment by typo3max** [comment]
Danke Holzinger, mache ich.

**Comment by franzholz** [comment]
You need to set `emailCheck = 0` . Or you must enable all of the ports 25, 587, 2525 to be connected to from your server.  Maybe port 25 would be sufficient.

**Comment by typo3max** [comment]
OK machen sie das emailcheck 0, hoffentlich kann man dann Beiträge posten endlich danke.
________________________________
Von: Franz Holzinger ***@***.***>
Gesendet: Mittwoch, 3. April 2024 23:11
An: franzholz/tt_board ***@***.***>
Cc: Maximilian Fasel ***@***.***>; Author ***@***.***>
Betreff: Re: [franzholz/tt_board] check of MX record for email fails (Issue #38)


You need to set emailCheck = 0 . Or you must enable all of the ports 25, 587, 2525 to be connected to from your server. Maybe port 25 would be sufficient.
