### ISSUE TITLE
Empty List with Typo3 9.5.11

### ISSUE THREAD

**Issue by martinKoske** [franzholz/tt_board#5]
hi,

I have a customer with an TYPO3 8 and I need an upgarde to 9.
have you tried tt_board with TYPO3 9.5.11?

I had some some php warnings in BE from ext_localconf and fixed them.
Added the Typoscript manually but still nothing in the FE.

Any hints? Are you working on it?

regards
martin

**Comment by franzholz** [comment]
**Yes, TYPO3 9 support is still needed!**

**Comment by franzholz** [comment]
Try to install to extension typo3db_legacy. However more things must be changed. I will start with it in the next days.

**Comment by franzholz** [comment]
tt_board 1.10.15 works under TYPO3 9.5. The extension typo3db_legacy must be installed.
